// Notifications
export const PUSH_NOTIFICATION = "NOTIFICATIONS/MUTATE_SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "NOTIFICATIONS/MUTATE_REMOVE_NOTIFICATION";

// Users
export const SET_USERS = "USERS/MUTATE_SET_USERS";
export const SET_IS_LOGINED = "USERS/MUTATE_SET_IS_LOGINED";
export const SET_TODOS = "USERS/MUTATE_SET_TODOS";
export const ADD_NEW_TODO = "USERS/MUTATE_ADD_NEW_TODO";
export const SET_NEW_TODO_STATUS = "USERS/MUTATE_SET_NEW_TODO_STATUS";
export const SET_NEW_FAVORITE_STATUS = "USERS/MUTATE_SET_NEW_FAVORITE_STATUS";
export const SET_CURRENT_USER = "USERS/MUTATE_SET_CURRENT_USER";
